#!/usr/bin/env bash
# Print “To infinity and beyond” forever; on SIGTERM say “I am invincible!!!” and keep running
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done
OA
