#!/usr/bin/env bash
#!/bin/bash

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap the SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

echo "Starting 7-highlander..."

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
