#!/usr/bin/env bash
# Print “To infinity and beyond” forever; shout “I am invincible!!!” on SIGTERM
trap 'echo "I am invincible!!!"' TERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done
